name: Push geometry file to site

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/checkout@v4
        with:
          repository: luke-hoffmann/luke-hoffmann.github.io
          token: ${{ secrets.REPO_B_TOKEN }}
          path: site

      - run: |
          mkdir -p site/geometry
          cp dist/index.global.js site/assets/js/lib/geometry/index.global.js

      - run: |
          cd site
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add geometry/index.global.js
          git commit -m "Update geometry build" || exit 0
          git push
